[build]
  publish = "dist" # or "build" depending on your framework
  command = "npm run build"


[build.environment]
  SECRETS_SCAN_ENABLED = "false"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"